parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: sigcot
    database_user: root
    database_password: '123456'
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: a06f0e2103332e05d2a66c5e3ac8836e10
    database_path: null
