<?php

namespace Sigcotweb\AplicativoBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CaretirosController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Sigcotweb\AplicativoBundle\Controller\CaretirosController();
        return $instance;
    }
}
