<?php

namespace Proxies\__CG__\Sigcotweb\AplicativoBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Cooperativistas extends \Sigcotweb\AplicativoBundle\Entity\Cooperativistas implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setUsuario($usuario)
    {
        $this->__load();
        return parent::setUsuario($usuario);
    }

    public function getUsuario()
    {
        $this->__load();
        return parent::getUsuario();
    }

    public function setClave($clave)
    {
        $this->__load();
        return parent::setClave($clave);
    }

    public function getClave()
    {
        $this->__load();
        return parent::getClave();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setApellido($apellido)
    {
        $this->__load();
        return parent::setApellido($apellido);
    }

    public function getApellido()
    {
        $this->__load();
        return parent::getApellido();
    }

    public function setCinum($cinum)
    {
        $this->__load();
        return parent::setCinum($cinum);
    }

    public function getCinum()
    {
        $this->__load();
        return parent::getCinum();
    }

    public function setRifnum($rifnum)
    {
        $this->__load();
        return parent::setRifnum($rifnum);
    }

    public function getRifnum()
    {
        $this->__load();
        return parent::getRifnum();
    }

    public function setDireccion($direccion)
    {
        $this->__load();
        return parent::setDireccion($direccion);
    }

    public function getDireccion()
    {
        $this->__load();
        return parent::getDireccion();
    }

    public function setTelefonos($telefonos)
    {
        $this->__load();
        return parent::setTelefonos($telefonos);
    }

    public function getTelefonos()
    {
        $this->__load();
        return parent::getTelefonos();
    }

    public function setFoto($foto)
    {
        $this->__load();
        return parent::setFoto($foto);
    }

    public function getFoto()
    {
        $this->__load();
        return parent::getFoto();
    }

    public function setCiarc($ciarc)
    {
        $this->__load();
        return parent::setCiarc($ciarc);
    }

    public function getCiarc()
    {
        $this->__load();
        return parent::getCiarc();
    }

    public function setRifarc($rifarc)
    {
        $this->__load();
        return parent::setRifarc($rifarc);
    }

    public function getRifarc()
    {
        $this->__load();
        return parent::getRifarc();
    }

    public function setDccargo(\Sigcotweb\AplicativoBundle\Entity\Dccargos $dccargo = NULL)
    {
        $this->__load();
        return parent::setDccargo($dccargo);
    }

    public function getDccargo()
    {
        $this->__load();
        return parent::getDccargo();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'usuario', 'clave', 'nombre', 'apellido', 'cinum', 'rifnum', 'direccion', 'telefonos', 'foto', 'ciarc', 'rifarc', 'dccargo');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}