<?php

namespace Proxies\__CG__\Sigcotweb\AplicativoBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Dcactivos extends \Sigcotweb\AplicativoBundle\Entity\Dcactivos implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTipo($tipo)
    {
        $this->__load();
        return parent::setTipo($tipo);
    }

    public function getTipo()
    {
        $this->__load();
        return parent::getTipo();
    }

    public function setMarca($marca)
    {
        $this->__load();
        return parent::setMarca($marca);
    }

    public function getMarca()
    {
        $this->__load();
        return parent::getMarca();
    }

    public function setModelo($modelo)
    {
        $this->__load();
        return parent::setModelo($modelo);
    }

    public function getModelo()
    {
        $this->__load();
        return parent::getModelo();
    }

    public function setAnio($anio)
    {
        $this->__load();
        return parent::setAnio($anio);
    }

    public function getAnio()
    {
        $this->__load();
        return parent::getAnio();
    }

    public function setPlaca($placa)
    {
        $this->__load();
        return parent::setPlaca($placa);
    }

    public function getPlaca()
    {
        $this->__load();
        return parent::getPlaca();
    }

    public function setCooperativista(\Sigcotweb\AplicativoBundle\Entity\Cooperativistas $cooperativista = NULL)
    {
        $this->__load();
        return parent::setCooperativista($cooperativista);
    }

    public function getCooperativista()
    {
        $this->__load();
        return parent::getCooperativista();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'tipo', 'marca', 'modelo', 'anio', 'placa', 'cooperativista');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}