parameters:
#    aplicativo.example.class: Sigcotweb\AplicativoBundle\Example

services:
#    aplicativo.example:
#        class: %aplicativo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
